### ISSUE TITLE
Rebuild files from offline website gov.uk

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-glasswall-rebuild#34]
- Rebuild all files from the offline site
- Provide XML result's file (store them in S3)

Offline site is available here: http://18.134.12.200/
Files: https://k8-mass-download.s3.eu-west-2.amazonaws.com/gov_Files.zip

**Comment by yardenshoham** [comment]
https://glasswallsolu-qbp1117.slack.com/archives/C01ALAT5ALT/p1603011821083900

Resulting bucket: https://s3.console.aws.amazon.com/s3/buckets/gov-xml-reports/?region=us-east-2&tab=overview
